#!/usr/bin/env python

import sys
import smtplib
import getpass

#	get main script parameters
hostname = raw_input('Enter mail service: ')
username = raw_input('Enter username: ')
password = getpass.getpass('Password: ')

#	trying to connect the chosen mail service 
#	with provided username and password
try:
	smtp = smtplib.SMTP_SSL('smtp.' + hostname)
	smtp.login(username, password)
	smtp.ehlo()
except smtplib.SMTPConnectError:
	print('\nConnection refused, check your attributes.')
except Exception as e:
	print('\nUnexpected error: %s' % e)
else:
	#	get reciever and format message to acceptable view
	receiver = raw_input('\nConnection succeeded...\n'+
			     '\nEnter receiver email: ')
	message = raw_input('\nEnter the message: \n')
	
	message = '''From: {}
		To: {}
	 	Subject: {}
								
		{}
	'''.format(username, receiver, '', message).replace('\t','')	

	#	some kind of switch-case (just for practise):
	#	ask if user really want to send his message
	statement = { 'y' : 1, 'n' : 0  }
	answer = raw_input('\nSend this message' + 
			   ' to %s? (y/n)\n' % receiver).lower()
	if answer in statement:
		if statement[answer]:
			smtp.sendmail(username, [receiver], message)
		elif not statement[answer]:
			print('Sending refused. Exiting...')
	else:
		print('Unknown character. Sending refused.')
	
	smtp.quit()


